#
# Use Manorrock Server
#
FROM manorrock/server:amd64-v20.6.0

#
# Copy Manorrock Korat into Tomcat 9.
#
COPY target/korat.war /usr/local/tomcat/webapps/ROOT.war

#
# Add the Manorrock Korat distribution.
#
ADD target/korat.tar.gz /root/.manorrock

#
# Set the work directory
#
WORKDIR /root/.manorrock/korat

#
# Setup command to start Tomcat with console output.
#
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]